### ISSUE TITLE
Verify that test resources actually compile

### ISSUE THREAD

**Issue by slarse** [SpoonLabs/diffmin#37]

**Comment by algomaster99** [comment]
@slarse Can you tell me where exactly this step has been incorporated in [sorald](https://github.com/SpoonLabs/sorald)? I wanted to know how I can modify the test phase of maven so that it verifies the test resources too rather than just putting them in `target/test-classes`.

**Comment by slarse** [comment]
It's implicitly part of a couple of other tests where we use Spoon's `MavenLauncher` to build produce a full classpath model (a model where all references are resolved).

For you, it's probably easiest to just write a small Python script or the like that renames the Java files appropriately and compiles them one-by-one. As a very bare-minimum effort, you could use `Environment.setShouldCompile(true)` in Spoon itself, but that doesn't work well when it comes to parsing invalid syntax (it misses a lot of things, it's mostly useful for verifying transformations).
