### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#42]
Currently, `App` contains the entire logic of patch generation and application but it would be better if we can segregate the classes for `PatchGeneration`, `PatchApplication`, and the `MainClass`. `PatchGeneration` and `PatchApplication` can be further subdivided according to the 4 different operations. Its benefits:

1. I feel this would help in writing the logic for `MoveOperation` as we can simply convert it to - `DeleteOperation` + `InsertOperation`. In other words, we can delete the `srcNode` and insert the `dstNode`. `PatchApplication` and `PatchGeneration`  can also be under the same class as two methods - `generate` and `apply` but that would require us to write class methods in the class rather than static methods. I am yet to find out which is more convenient to write and test.

2. `MainClass` can contain the  logic for combining the patch generation and application so that it can be reused when running the tests or the command-line app.

**Comment by slarse** [comment]
This sounds like a very good refactoring!

**Comment by algomaster99** [comment]
Resolved by #48, #60, and #61.
