### ISSUE TITLE
Approach to write generation of Move Operation

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#43]
Reference: https://github.com/SpoonLabs/diffmin/issues/42#issue-874023869

Implementing like in this issue above would generate two corresponding patches for each `MoveOperation`. Moreover, the essence of _moving_ a statement/parameter etc is lost.

A better way could be to store the indices of the `srcNode` and `dstNode` in the old and new collection and then perform the following processes:

1. Removal of `srcNode` - Use APIs like [`removeStatement`](https://github.com/INRIA/spoon/blob/fecec810886819c09ffc4955faeb4f50f64e07a3/src/main/java/spoon/reflect/code/CtStatementList.java#L117) (should we consider writing API for `removeStatementAt`? Otherwise we would have to use `removeStatement(getStatement)` but I am fine with either) to remove the `srcNode`. I have one question here - if we remove a statement this way, would it leave an empty line there or delete the entire line?

2. Addition of `dstNode` - We can reuse the logic for applying insert patches.

**Comment by slarse** [comment]
> Removal of srcNode - Use APIs like removeStatement (should we consider writing API for removeStatementAt?

I suggest using `srcNode.delete()`.

> I have one question here - if we remove a statement this way, would it leave an empty line there or delete the entire line?

Deleting a statement removes it from the model, and thus it is not printed. The statement simply is not printed. Perhaps it would be a good idea for you to run some debugging with the `DefaultJavaPrettyPrinter` to see how it prints elements. We can have a look at that during this week's meeting.

> Addition of dstNode - We can reuse the logic for applying insert patches.

That seems reasonable.
