### ISSUE TITLE
Integrate sorald with diffmin

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#50]
I was thinking if we should integrate `sorald` in our workflow. It can tell us about the warnings in our code and can even repair them. One `sorald-buildbreaker` is released, we could integrate that action too.

**Comment by slarse** [comment]
Great idea! We can use `sorald-buildbreaker` right away, [see the config in the Sorald repo](https://github.com/SpoonLabs/sorald/blob/master/.github/workflows/sorald_buildbreaker.yml).
