### ISSUE TITLE
Implementation of inserting `ThrownType`s

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#55]
I was working on inserting `Exception`s' signature to `CtExecutable` such as following.

**PREV_Demo.java**
```java
class Demo {
    public void func() throws SecurityException { }
}
```

**NEW_Demo.java**
```java
class Demo {
    public void func() throws SecurityException, ExceptionInInitializerError { }
}
```

Unlike the other collections, `getThrownTypes()` returns a [set](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/declaration/CtExecutableImpl.java#L135) of these exceptions [sorted on the basis of their qualified names](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/reflect/declaration/CtExecutableImpl.java#L146). Since this is a sorted set, `addThrownTypeAt` does not make sense but `addThrownType` does. Prior to implementing that, I had one question. **Why is it sorted on the basis of the qualified names?** It did not seem necessary to me to sort them because I was able to compile a Java program irrespective of the order of the exception's signature. Moreover, this would pose a problem for `diffmin` as the order would be sorted after the patch but it would not be expected so comparing their pretty-prints will raise an `AssertionError`.

**Comment by slarse** [comment]
I think for sets and maps, we're better of _not_ doing precise insertions, i.e. we just insert the entire collection as-is instead (here, using `setThrownTypes`).

There's no easy way to control the order of elements, in fact the order of elements for `QualifiedNameBasedSortedSet` is rather more complex than just the qualified names (see inria/spoon#3355). With deep knowledge of implementation details, we could implement some hacks to control the order of elements, but that's really too much effort here and might break if Spoon internals are changed.
