### ISSUE TITLE
Refactor logic for retrieving test resources

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#63]
A better method is needed than to manually configure the subdirectory every time a new operation or a mixture of operation is tested. For example, #62 required to configure the `move` directory manually in `AppTest`.

1. One solution to avoid this is to recursively iterate over the `src/test/resource` directory and feed the resources to the tests. Further, we can name the test case on the basis of the deepest directory which would contain the two files - `PREV` and `NEW`.
2. Since we know that we will only have three levels of directory, we don't need to use recursion. We can instead use fixed number of `for-loop`s. This solution will provide us with more control over how we can name our test cases.
    ```sh
    resources
   ├── delete
   │   ├── entire_file
   │   │   ├── NEW_EntireFile.java
   │   │   └── PREV_EntireFile.java

    ```

**Comment by slarse** [comment]
> A better method is needed than to manually configure the subdirectory every time a new operation or a mixture of operation is tested

While it's not too hard to do that, you would end up with just one concrete test method for all of the end-to-end tests. That's a bit annoying when you just want to run, for example, the insertion tests. Or the move tests. While it's relatively easy to select a specific parameterization of a test in IntelliJ, that's not necessarily the case for other test runners.

The easiest solution, I think, is to keep pure insert, move, update and deletes as separate concrete tests, and then have a final one just called "mix" or something like that. Combining everything into a single parameterized test is somewhat overautomating this problem, I think.

**Comment by algomaster99** [comment]
> The easiest solution, I think, is to keep pure insert, move, update and deletes as separate concrete tests, and then have a final one just called "mix" or something like that.

Sounds like a better solution. If anyone still needs to run a specific test, they may refer to [this article](https://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html).

**Comment by algomaster99** [comment]
Will work on this once #66 is merged.
