### ISSUE TITLE
Pretty-printing the model after fetching the first type is not _always_ correct

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#72]
The structure test might yield false result when there is an insertion of a `CtType` in the compilation unit and package. This is because we pretty-print the patched model by [getting the first type in the model](https://github.com/SpoonLabs/diffmin/blob/2057a911fdf208a23b0ca39040104a2d1055d680/src/main/java/com/diffmin/util/SpoonUtil.java#L83). That first type could _sometimes_ be the inserted node and belong to the `NEW` compilation unit. So essentially we would be pretty-printing the `NEW` file and checking it with the `NEW` program itself!

I think this can be solved by making sure the compilation unit of a node is changed whenever it is transferred to some other compilation unit (`PREV` in our case). But the compilation unit attached to the `SourcePosition` should not change as that will help us in checking element's origin. This solution is somewhat inspired from the discussion [here](https://github.com/INRIA/spoon/issues/3942#issuecomment-846880720).

**Comment by algomaster99** [comment]
We can probably implement `setters` and `getters` of `CtCompilationUnit` in `CtElement.java`. The setters can be used in [`ContextBuilder.java#enter`](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/compiler/jdt/ContextBuilder.java#L87) to set the initial compilation unit of each element. We will also have to use this setters in `replace`, `insert`, etc APIs so that the compilation unit attached to element is changed when the model is changed.

We can keep the compilation unit we get from source position as it is as that compilation unit will tell the _source_ compilation unit while `CtElement.getCompilationUnit` will point to the current compilation unit.

@slarse what do you think about this approach?

**Comment by slarse** [comment]
The problem is that only the first type is pretty printed. The solution is to pretty print all types.

The pretty printing test should run the entire application instead of cobbling together a few parts of it. It's only for the element origin test that the patched model is actually needed.

**Comment by algomaster99** [comment]
> The problem is that only the first type is pretty printed. The solution is to pretty print all types.

We get the compilation unit using the first type and then we pretty-print the compilation unit. So in some cases the first type can be from `NEW.java` and its compilation unit will be `NEW.java` even though it has moved to the model corresponding to `PREV.java`.

> So, I'd solve this by creating a patch(File, File) method in Main and have that just return a String with the pretty printed compilation unit.

We already have a `patchAndGenerateModel(File, File)` method which returns the `patchedModel`. Is there a better way to pretty-print this without using the first type? We would need a more generic way.

**Comment by slarse** [comment]
> > The problem is that only the first type is pretty printed. The solution is to pretty print all types.
> 
> We get the compilation unit using the first type and then we pretty-print the compilation unit. So in some cases the first type can be from `NEW.java` and its compilation unit will be `NEW.java` even though it has moved to the model corresponding to `PREV.java`.

Ah, right now I get it. This is back to the problem that there's no real way to get the _current_ compilation unit of an element. But, each model should only have one compilation unit, right? So if we change `displayModifiedModel` (which should be renamed btw, it has nothing to do with modifications anymore) to displaying the first compilation instead, it should work. I.e. something like this:

```java
        List<CtCompilationUnit> compilationUnits = List.copyOf(
                model.getUnnamedModule().getFactory().CompilationUnit().getMap().values());

        if (compilationUnits.size() != 1) {
            throw new IllegalArgumentException("model must have precisely one compilation unit, but has: " + compilationUnits);
        }

        CtCompilationUnit cu = compilationUnits.get(0);
```

That should solve it, we get the compilation unit from the model instead of from the type.

> > So, I'd solve this by creating a patch(File, File) method in Main and have that just return a String with the pretty printed compilation unit.
> 
> We already have a `patchAndGenerateModel(File, File)` method which returns the `patchedModel`. Is there a better way to pretty-print this without using the first type? We would need a more generic way.

So this is somewhat unrelated, but yes there should be a method `patchAndPrint(File, File)` that returns the String, such that the test doesn't need to do all of this:
https://github.com/SpoonLabs/diffmin/blob/10aebe4aa437b83a8d88f1baf1bdf13ab1e8b9ba/src/test/java/com/diffmin/StructureTest.java#L54-L67

Branching in tests is generally a bad sign.

**Comment by algomaster99** [comment]
> That should solve it, we get the compilation unit from the model instead of from the type.

Thanks! Seems exactly like what I would need :)

> Branching in tests is generally a bad sign.

Okay. I will keep this in mind.

**Comment by slarse** [comment]
Note that the fact that we can't get the current compilation unit from an element is still a problem in Spoon IMO, it should be possible without jumping through hoops like this.

**Comment by slarse** [comment]
> > But, each model should only have one compilation unit, right?
> 
> It will have the `package-info.java` file as well. Can we filter that out? ~I have a feeling there will be a constant in spoon assigned to name the `package-info.java` file~

Not unless you create it, i.e. it's not there by default. I think I commented somewhere where you created a `package-info.java` compilation unit.
