### ISSUE TITLE
Upgrading Java version

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#82]
Currently, `diffmin` compiles to Java 11. I was thinking to upgrade it as it would allow incorporating more features of Java. For example, switch expressions. They were standardised in version 14. Moreover, `spoon` also supports up to Java 15.

**Comment by slarse** [comment]
I think you might be thinking about this a bit sideways. Spoon supports analyzing source code up to Java 15, but it's compiled with Java 8. The JDK version diffmin targets for compilation does not limit what diffmin can analyze, it only limits which JDKs can be used to run it.

**Comment by algomaster99** [comment]
Thanks for the clarification. I would like to keep compiling the code with Java 11 only then. However, I can modify the [step in the workflow](https://github.com/SpoonLabs/diffmin/blob/main/.github/workflows/maven.yml#L40) so that `verify-test-resources.sh` use Java 15 for compiling.

**Comment by slarse** [comment]
Yep, you could do that.
