### ISSUE TITLE
Configure linter

### ISSUE THREAD

**Issue by algomaster99** [SpoonLabs/diffmin#85]
Checkstyle's configuration was deleted in https://github.com/SpoonLabs/diffmin/pull/27. It would be good to bring it back.

**Comment by slarse** [comment]
Do you have any non-formatting rule in mind? Because everything that has to do with formatting is handled by the auto-formatter.

**Comment by algomaster99** [comment]
One purpose was to check if all public methods have JavaDoc. There are many rules written [here](https://checkstyle.sourceforge.io/checks.html) which might be helpful too. For example, [`SimplifyBooleanExpression`](https://checkstyle.sourceforge.io/config_coding.html#SimplifyBooleanExpression), [`CheckForFallThrough`](https://checkstyle.sourceforge.io/config_coding.html#FallThrough), etc.

**Comment by slarse** [comment]
Sure, you could use such checks. I'd just advise avoiding formatting checks, and let the auto-formatter deal with such.

**Comment by algomaster99** [comment]
> I'd just advise avoiding formatting checks, and let the auto-formatter deal with such.

Right. I will have to be careful there because I don't want to introduce conflict rules or redundant rules.
